### ISSUE TITLE
improve the way you can configure the database

### ISSUE THREAD

**Issue by oupala** [hedgedoc/container#114]
As discussed in another issue (codimd/server#364), @SISheogorath explained a bit about how to configure the database with environment variables (with a default hard-coded fallback).

This is due to the following lines:

https://github.com/codimd/container/blob/7cf4194ca07628ab19f2becc4ed60dd10815d5ec/resources/docker-entrypoint.sh#L21-L23

Hard-coding a default fallback seems to be a dev-oriented hack but should not appear in production, IMHO. There could be people declaring a postgres database with `hackmd:hackmdpass` login and pass to make it work. Hard-coding password is a bad habit and lowers security level. It should be avoided.

In addition, the [codimd server documentation](/codimd/server/blob/master/docs/configuration.md#codimd-basics) states that the default value of `CMD_DB_URL` is undefined (which is a good thing) while this default value changes in [codimd container](/codimd/container) without being documented.

I clearly think that the codimd container should be usable for most of the usecases without requiring a custom build.

In my case the database credential are offered by the platform as individual variables:

- `CMD_DB_URL` (ip and port of the database)
- `CMD_DB_NAME`
- `CMD_DB_LOGIN`
- `CMD_DB_PASSWORD`

and I don't have an easy way to concatenate them into a `CMD_DB_URL` as expected by the `docker-entrypoint.sh` script.

Could we make it clear in the issue to explain the pro and cons of each way of configuring the database?

- `db` object in the config file
- `dbURL` object in the config file
- `CMD_DB_URL` environment variable

We should also explain the constraints that exists with included libraries (I'm thinking about [sequelize](https://sequelize.readthedocs.io/en/latest/api/sequelize/) which might add some constraints.

In the end, I would love to be able to use automatic provisionning of my database in a k8s context. I currently have to use a 3 steps deployement:

1. deploy the database
2. get the automatically created credentials and manually concatenate them into a single `CMD_DB_URL` string
3. deploy codimd with the previous concatenated string into an environment variable

Whereas I could use another feature of k8s to automatically inject maria db password into codimd configuration:

```yaml
          - name: CMD_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MARIA_APP_PASSWORD
                name: codimd-db-staging-secret
```

This would add **automation** and **security**, both at one time.

What do you think?

**Comment by hugopeixoto** [comment]
I don't use k8s, so sorry if this sounds completely wrong, but could you define your pod like this?

```yaml
      env:
          - name: CMD_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MARIA_APP_PASSWORD
                name: codimd-db-staging-secret
        - name: CMD_DB_URL
          value: "mysql://$(CMD_DB_LOGIN):$(CMD_DB_PASSWORD)@$(CMD_DB_HOSTANDPORT)/$(CMD_DB_NAME)"
```

**Comment by oupala** [comment]
No, this does not work as the variable does not get interpreted by k8s:

```yaml
            value: 'mysql://${CMD_DB_USER}:${CMD_DB_PASSWORD}@myq-mariadb-staging-service-sql:3306/hedgedoc-db'
          - name: CMD_DB_USER
            value: 'hedgedoc-db-user'
```

leads to the following logs:

```log
Parsed url mysql://${CMD_DB_USER}:*****@mariadb-service-sql:3306/hedgedoc-db

[ERROR:[Access denied for user '${CMD_DB_USER}'@'10.19.2.11' (using password: YES)
```

**Comment by oupala** [comment]
No, this does not work as the variable does not get interpreted by k8s:

```yaml
            value: 'mysql://${CMD_DB_USER}:${CMD_DB_PASSWORD}@mariadb-service-sql:3306/hedgedoc-db'
          - name: CMD_DB_USER
            value: 'hedgedoc-db-user'
```

leads to the following logs:

```log
Parsed url mysql://${CMD_DB_USER}:*****@mariadb-service-sql:3306/hedgedoc-db

[ERROR:[Access denied for user '${CMD_DB_USER}'@'10.19.2.11' (using password: YES)
```

**Comment by oupala** [comment]
No, this does not work as the variable does not get interpreted by k8s:

```yaml
          - name: CMD_DB_URL
            value: 'mysql://${CMD_DB_USER}:${CMD_DB_PASSWORD}@mariadb-service-sql:3306/hedgedoc-db'
          - name: CMD_DB_USER
            value: 'hedgedoc-db-user'
```

leads to the following logs:

```log
Parsed url mysql://${CMD_DB_USER}:*****@mariadb-service-sql:3306/hedgedoc-db

[ERROR:[Access denied for user '${CMD_DB_USER}'@'10.19.2.11' (using password: YES)
```
