### ISSUE TITLE
Database name seems to be hardcoded

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/container#136]
@ErikMichelson and I noticed a very weird behavior:

1. Use the example `docker-compose.yml` with MariaDB
```yaml
version: '3'
services:
  database:
    image: mariadb:10
    environment:
      - MYSQL_USER=hedgedoc
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=hedgedoc
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - database:/var/lib/mysql
      - ./resources/utf8.cnf:/etc/mysql/conf.d/utf8.cnf
    networks:
      backend:
    restart: always
  app:
    image: quay.io/hedgedoc/hedgedoc:1.6.0
    environment:
      - CMD_DB_URL=mariadb://hedgedoc:password@database:3306/hedgedoc
    volumes:
      - uploads:/hedgedoc/public/uploads
    ports:
      - "3000:3000"
    networks:
      backend:
    restart: always
    depends_on:
      - database
networks:
  backend:
volumes:
  database:
  uploads:
```
2. Start the stack. Everything starts up normally.
3. Change the image to `quay.io/codimd/server:1.6.0`, `down` and `up` the stack.
4. HedgeDoc now fails to start:
```
app_1       | Sequelize CLI [Node: 12.19.0, CLI: 5.5.1, ORM: 5.21.4]
app_1       | 
app_1       | Parsed url mariadb://hedgedoc:*****@database:3306/hedgedoc
app_1       | warning: please use IANA standard timezone format ('Etc/GMT0')
app_1       | warning: please use IANA standard timezone format ('Etc/GMT0')
app_1       | No migrations were executed, database schema was already up to date.
database_1  | 2020-12-03  9:43:54 5 [Warning] Aborted connection 5 to db: 'hedgedoc' user: 'hedgedoc' host: '172.23.0.3' (Got an error reading communication packets)
app_1       | 2020-12-03T09:43:57.532Z warn: 	Neither 'domain' nor 'CMD_DOMAIN' is configured. This can cause issues with various components.
app_1       | Hint: Make sure 'protocolUseSSL' and 'urlAddPort' or 'CMD_PROTOCOL_USESSL' and 'CMD_URL_ADDPORT' are configured properly.
app_1       | 2020-12-03T09:43:57.534Z warn: 	Session secret not set. Using random generated one. Please set `sessionSecret` in your config.js file. All users will be logged out.
app_1       | 2020-12-03T09:43:57.535Z warn: 	PDF export was disabled for this release to mitigate a critical security issue. This feature will hopefully become available again in future releases.
app_1       | Thu, 03 Dec 2020 09:43:57 GMT hsts deprecated The "includeSubdomains" parameter is deprecated. Use "includeSubDomains" (with a capital D) instead. at app.js:85:18
app_1       | warning: please use IANA standard timezone format ('Etc/GMT0')
app_1       | warning: please use IANA standard timezone format ('Etc/GMT0')
app_1       | Unhandled rejection SequelizeDatabaseError: (conn=7, no: 1142, SQLState: 42000) SELECT command denied to user 'hedgedoc'@'172.23.0.3' for table 'Users'
app_1       | sql: SHOW INDEX FROM `Users` FROM `hackmd` - parameters:[]
app_1       |     at Query.formatError (/codimd/node_modules/sequelize/lib/dialects/mariadb/query.js:285:16)
app_1       |     at /codimd/node_modules/sequelize/lib/dialects/mariadb/query.js:68:22
app_1       |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
The two `FROM`s in `sql: SHOW INDEX FROM `Users` FROM `hackmd` - parameters:[]` look like Sequelize is for some reason trying to use a `hackmd` database. Note that the URL still uses `hedgedoc` and the `sequelize-cli` uses the correct database to check for migrations.

This problem seems to also occur the other way round: If you previously deployed the old `codimd/server` image and used a database named `hackmd` ([the default](https://github.com/hedgedoc/container/commit/298f793c5c59984979b6561261d6c418d7a003ef#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3L70) before 298f793c5c59984979b6561261d6c418d7a003ef) and now upgrade to a image under `hedgedoc/hedgedoc` without touching anything else, HedgeDoc fails to connect to the database (as it wants to use `hedgedoc`).

So it looks like we use a database called `hackmd` for images before 298f793c5c59984979b6561261d6c418d7a003ef and a database called `hedgedoc` for images after that, regardless of what is configured in `CMD_DB_URL`?
