### ISSUE TITLE
Debian version fails to build with docker-compose due to $UID issue

### ISSUE THREAD

**Issue by zeigerpuppy** [hedgedoc/container#144]
Step 34 of the build fails with the following error:

```
Step 34/46 : COPY --chown=$UID --from=builder /hedgedoc /hedgedoc
ERROR: Service 'hedgedoc' failed to build: unable to convert uid/gid chown string to host mapping: can't find uid for user $UID: no such user: $UID
```

It's a bit strange as the `UID` argument is specified in the `Dockerfile`.
I have worked around this by hardcoding the line, but I'm sure there's a good reason for why this is failing

```
COPY --chown=10000 --from=builder /hedgedoc /hedgedoc
```

**Comment by SISheogorath** [comment]
What version of docker are you running?

**Comment by zeigerpuppy** [comment]
Docker version 17.12.0-ce, build c97c6d6
docker-compose version 1.23.0, build c8524dc1
Debian9

It's a little bit of an unusual configuration in that we also use [kata-containers](https://github.com/kata-containers/kata-containers) as the runtime, but this usually has no effect on the parsing of dockerfile variables.  The major substantive change it makes is in the explicit networking.

I have included my docker-compose.yml (sanitised) below for reference

```yaml
# Hedgedoc
version: '3'
services:

  hedgedocpostgres:
    # Don't upgrade PostgreSQL by simply changing the version number
    # You need to migrate the Database to the new PostgreSQL version
    image: postgres:9.6-alpine
    container_name: hedgedoc-postgres
    expose:
      - "5432"
    networks:
      docker2:
        ipv4_address: 192.12.18.27
    volumes:
      - postgresql:/var/lib/postgresql/data
      - /docker_config/dns/resolv.conf:/etc/resolv.conf
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=hedgedocpass
      - POSTGRES_DB=hedgedoc
    restart: always


  hedgedoc:
    # Uncomment the following section to build the image yourself:
    build:
      context: ../HedgeDoc-docker-container
      dockerfile: debian/Dockerfile
      args:
        VERSION: master
        HEDGEDOC_REPOSITORY: https://github.com/hedgedoc/hedgedoc.git
        # UID: 10000
        # we have had to hardcode UID in Dockerfile currently - see https://github.com/hedgedoc/container/issues/144
    #image: quay.io/hedgedoc/hedgedoc:1.7.1
    container_name: hedgedoc
    depends_on:
      - hedgedocpostgres
    volumes:
      - uploads:/hedgedoc/public/uploads
      - ${PWD}/themes/reveal.js:/hedgedoc/public/build/reveal.js
      - ${PWD}/themes/css:/hedgedoc/public/css
      - /zpool2/docker_config/dns/resolv.conf:/etc/resolv.conf
    expose:
      - "3000"
    networks:
      docker2:
        ipv4_address:  192.12.18.25
    environment:
      - CMD_DB_URL=postgres://hedgedoc:hedgedocpass@hedgedoc-postgres:5432/hedgedoc
      - CMD_DOMAIN=hedgedoc.mydomain.net
      - CMD_PROTOCOL_USESSL=true
      - CMD_USECDN=false
      - CMD_URL_ADDPORT=false
      - CMD_ALLOW_FREEURL=true
# AUTH Options
      - CMD_ALLOW_EMAIL_REGISTER=false
      - CMD_EMAIL=true
      - CMD_GITLAB_SCOPE=api
      - CMD_GITLAB_BASEURL=https://gitlab.myserver.net
      - CMD_GITLAB_CLIENTID=********
      - CMD_GITLAB_CLIENTSECRET=**********
# Anonymous options
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
    restart: always

networks:
  docker2:
    external:
      name: docker2

# named volumes
volumes:
    # volume mounted on bindmount
    postgresql:
      driver: local
      driver_opts:
        type: 'none'
        device: '${PWD}/volumes/postgresql'
        o: 'bind'

    uploads:
      driver: local
      driver_opts:
        type: 'none'
        device: '${PWD}/volumes/uploads'
        o: 'bind'
```
