### ISSUE TITLE
configuration about passing CMD_DB_URL via secret

### ISSUE THREAD

**Issue by NigelBoxing** [hedgedoc/container#171]
if i want to fill the CMD_DB_URL with docker secrets instead of plain text 'protocol://username:password@database/port'
i need to fill it like this: 
```yaml
hedgedoc:
    environment:
        CMD_DB_URL=/run/secrets/dbURL 
    secrets:
       - dbURL
secrets:
    dbURL;
         file: ./dbURL.txt
```
because the code in resources/docker-entrypoint.sh defined 'dbURL'
```bash
DOCKER_SECRET_DB_URL_FILE_PATH="/run/secrets/dbURL"

if [ -f "$DOCKER_SECRET_DB_URL_FILE_PATH" ]; then
    CMD_DB_URL="$(cat $DOCKER_SECRET_DB_URL_FILE_PATH)"
fi

if [ "$CMD_DB_URL" = "" ]; then
    CMD_DB_URL="postgres://hedgedoc:password@database:5432/hedgedoc"
fi

export CMD_DB_URL
```
i am thinking whether it is appropriate, because i can not use the secret file whose name is not 'dbURL'
