### ISSUE TITLE
Can not allow anonymous edit

### ISSUE THREAD

**Issue by paulzhn** [hedgedoc/container#173]
Following the instructions of config, I have tried to set the env `CMD_ALLOW_ANONYMOUS_EDITS` to `'true'`, and even simply added the `config.allowAnonymousEdits = true` to the end of the` lib/config/index.js `. However, it just asked me to login, and the log showed `User doesn't have the right to edit`. Is there anything wrong?

My docker-compose.yml:

```yml
hedgedoc:
    # Uncomment the following section to build the image yourself:
    #build:
    #  context: .
    #  dockerfile: debian/Dockerfile
    #  args:
    #    - "VERSION=master"
    #    - "HEDGEDOC_REPOSITORY=https://github.com/hedgedoc/hedgedoc.git"
    image: quay.io/hedgedoc/hedgedoc:1.7.2
    #mem_limit: 256mb         # version 2 only
    #memswap_limit: 512mb     # version 2 only
    #read_only: true          # not supported in swarm mode, enable along with tmpfs
    #tmpfs:
    #  - /tmp:size=10M
    #  # Make sure you remove this when you use filesystem as upload type
    #  - /hedgedoc/public/uploads:size=10M
    environment:
      - CMD_ALLOW_ANONYMOUS_EDITS='true'
 ```
