### ISSUE TITLE
future of docker deployment

### ISSUE THREAD

**Issue by frankli0324** [hedgedoc/container#237]
> not bug, discussion

It came across my mind that since HedgeDoc 2.0 was designed to be a C/S app, and you used docker-compose for deployment in documentation, does that mean that the standalone image could be split into "backend" image and "frontend" image and be organized like:

```yml
services:
    frontend:
        image: frontendimg
        environments:
            BACKEND_WHATEVER_URL: http://backend:3000
        # other stuff
    backend:
        image: backendimg
        environments:
            # some env
    database:
        # some configurations
```

for extendability? maybe?

and could frontend image be like

```Dockerfile
FROM node AS builder
# build
FROM nginx
COPY --from=build dist www
```
