### ISSUE TITLE
MariaDB sample not working with MariaDB 10.6

### ISSUE THREAD

**Issue by agross** [hedgedoc/container#284]
I started with the sample docker-compose.yaml from this repo. The current MariaDB image is 10.6.5, but HedgeDoc is unable to connect to it. Possibly related to #47.

```
database_1   | 2022-01-27 17:26:40 0 [Note] mariadbd: ready for connections.
database_1   | Version: '10.6.5-MariaDB-1:10.6.5+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
database_1   | 2022-01-27 17:26:40 0 [Note] InnoDB: Buffer pool(s) load completed at 220127 17:26:40
app_1  | /bin/sh: git: not found
app_1  | 2022-01-27T17:27:14.199Z warn:         Database cannot be reached. Try 1 of 30.
app_1  | 2022-01-27T17:27:15.203Z warn:         Database cannot be reached. Try 2 of 30.
app_1  | 2022-01-27T17:27:16.207Z warn:         Database cannot be reached. Try 3 of 30.
app_1  | 2022-01-27T17:27:17.209Z warn:         Database cannot be reached. Try 4 of 30.
```

This is the sample composefile with adjustments for MariaDB

```yaml
version: '3'
services:
  # MySQL example
  # Most of the documentation that applies to PostgreSQL applies also to MySQL
  database:
     # You should be able to upgrade MySQL without problems
     # but to make sure no even when a problem appears you
     # should have a backup
     image: mariadb # mariadb:10.5 works!
     environment:
       - MYSQL_USER=hedgedoc
       - MYSQL_PASSWORD=password
       - MYSQL_DATABASE=hedgedoc
       - MYSQL_ALLOW_EMPTY_PASSWORD=true
     volumes:
       - database:/var/lib/mysql
       # This config provides UTF-8 support to the database by default
       # If this config is not used, HedgeDoc breaks as it tries to write
       # UTF-8 to a latin database.
       - ./utf8.cnf:/etc/mysql/conf.d/utf8.cnf
     networks:
       backend:
     restart: always

  app:
    # Uncomment the following section to build the image yourself:
    #build:
    #  context: .
    #  dockerfile: debian/Dockerfile
    #  args:
    #    - "VERSION=master"
    #    - "HEDGEDOC_REPOSITORY=https://github.com/hedgedoc/hedgedoc.git"
    image: quay.io/hedgedoc/hedgedoc:1.9.2
    #mem_limit: 256mb         # version 2 only
    #memswap_limit: 512mb     # version 2 only
    #read_only: true          # not supported in swarm mode, enable along with tmpfs
    #tmpfs:
    #  - /tmp:size=10M
    #  # Make sure you remove this when you use filesystem as upload type
    #  - /hedgedoc/public/uploads:size=10M
    environment:
      # **DB_URL** is formatted like: <databasetype>://<username>:<password>@<hostname>:<port>/<database>
      # Other examples are:
      # - mysql://hedgedoc:password@database:3306/hedgedoc
      # - sqlite:///data/sqlite.db (NOT RECOMMENDED)
      # - For details see the official sequelize docs: http://docs.sequelizejs.com/en/v3/
      - CMD_DB_URL=mysql://hedgedoc:password@database:3306/hedgedoc
      # **DOMAIN** is the domain under which HedgeDoc will be available. Just the (sub)domain, no protocol or paths.
      # You MUST change this if your instance should be available under another domain than "localhost", otherwise your
      # instance may be broken.
      # You can define only ONE domain.
      - CMD_DOMAIN=localhost
      # **PROTOCOL_USESSL** defines if generated links should be HTTPS URLs.
      # This variable won't activate encryption on the listen port.
      # Set this to true if your reverse proxy exposes your instance via HTTPS.
      - CMD_PROTOCOL_USESSL=false
      # **HSTS_ENABLE** defines if HSTS headers should be sent. Set this to true if you use HTTPS.
      - CMD_HSTS_ENABLE=false
      # **URL_ADDPORT** defines if generated links should contain the port.
      # Set this to false if your reverse uses the default ports (443 for HTTPS or 80 for HTTP).
      - CMD_URL_ADDPORT=true
    volumes:
      - uploads:/hedgedoc/public/uploads
    ports:
      # Ports that are published to the outside.
      # The latter port is the port inside the container. It should always stay on 3000
      # If you only specify a port it'll published on all interfaces. If you want to use a
      # local reverse proxy, you may want to listen on 127.0.0.1.
      # Example:
      # - "127.0.0.1:3000:3000"
      - "3000:3000"
    networks:
      backend:
    restart: always
    depends_on:
      - database

# Define networks to allow best isolation
networks:
  # Internal network for communication with PostgreSQL/MySQL
  backend:

# Define named volumes so data stays in place
volumes:
  # Volume for PostgreSQL/MySQL database
  database:
  uploads:
```
